spring.application.name=TLAGK

server.port=8081
spring.datasource.url=jdbc:sqlite:cart.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tăng thời gian chờ lock của JPA lên 30 giây (30000ms)
spring.jpa.properties.jakarta.persistence.lock.timeout=30000

# Đề phòng: Tăng thời gian chờ kết nối của connection pool
spring.datasource.hikari.connection-timeout=30000